export default {
  about: 'About',
  aboutInfo: 'Kothavada is a Rent Mangement App for Tenant and Landlord',
  all: 'All',
  add: 'Add',
  addNew: 'Add New',
  addPhoto: 'Add Photo',
  address: 'Address',
  addRent: 'Add Rent',
  addRoom: 'Add Room',
  addUpdate: 'Add/Update',
  addUpdateTenant: 'Add/Update Tenant',
  alreadySignedIn: 'Already Signed in',
  applyFilter: 'Apply Filter',
  appVersion: 'Kothavada 1.0',
  areYouSure: 'Are you sure you want to go back?',
  areYouSureAboutPayment: 'Are you sure about payment?',
  areYouSureToChange: 'Are you sure to change?',
  areYouSureToDelete: 'Are you sure to delete?',
  areYouSureToLogout: 'Are you sure you want to Logout?',
  cancel: 'Cancel',
  changePassword: 'Change Password',
  changeLanguage: 'Change Language',
  confirm: 'Confirm',
  customerFeedback: 'Customer Feedback',
  date: 'Date',
  delete: 'Delete',
  deletedSuccessfully: 'Deleted Successfully',
  editProfile: 'Edit Profile',
  electricityCharge: 'Electricity Charge',
  electricityPerUnit: 'Electricity Charge Per Unit',
  electricityUnit: 'Electricity Unit',
  endDate: 'End Date',
  english: 'English',
  enterDetails: 'Enter Details',
  enterMobile: 'Please enter Mobile',
  enterName: 'Please enter Name',
  enterPassword: 'Please enter Password',
  enterPrice: 'Please enter Price',
  enterRePassword: 'Please enter Retype Password',
  enterRoomName: 'Please enter Room name',
  enterFloor: 'Please select Floor',
  enterUserType: 'Please select User Type',
  feedbackemail: 'Enter your email',
  feedbackcontactnumber: 'Phone no',
  feedbackdescription: 'Write your message....',
  feedbacksubmit: 'SUBMIT',
  f_email: 'Email',
  f_contactnumber: 'Contact Number',
  f_description: 'Description',
  feedback: 'Feedback',
  flat: 'Flat',
  floor: 'Floor',
  fromDate: 'From',
  full: 'Full',
  fullName: 'Full Name',
  forgotPassword: 'Forgot Password',
  garbageCharge: 'Garbage Charge',
  haveAnAccount: 'Have an account?',
  internetCharge: 'Internet Charge',
  kothaVada: 'Kothavada',
  landlord: 'Landlord',
  loading: 'Loading...Please wait',
  login: 'Login',
  logout: 'Logout',
  matchPassword: 'Password did not match',
  mobile: 'Mobile',
  name: 'Name',
  nepali: 'नेपाली',
  newUser: 'New User',
  no: 'No',
  noNotifications: 'No Notifications',
  noPendingRents: 'No pending rents',
  noRoomsAvailable: 'No Rooms Available',
  notifications: 'Notifications',
  occupancy: 'Occupancy',
  paid: 'Paid',
  paidRent: 'Paid Rent',
  pay: 'Pay',
  payment: 'Payment',
  password: 'Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  pendingRent: 'Pending Rent',
  pendingRents: 'Pending Rents',
  pleaseEnterRent: 'Please Enter Rent',
  phone: 'Phone',
  previousDue: 'Previous Due',
  price: 'Price',
  profile: 'Profile',
  register: 'Register',
  rent: 'Rent',
  rentPaidSuccessfully: 'Rent Paid Successfully',
  rentPayment: 'Rent Payment',
  rentDetails: 'Rent Details',
  rentsLoadedSuccessfully: 'Rents Loaded Successfully',
  rentType: 'Rent Type',
  retypePassword: 'Retype Password',
  room: 'Room',
  roomDetails: 'Room Details',
  roomName: 'Room Name/No.',
  roomRent: 'Room Rent',
  roomSavedSuccessfully: 'Room Saved Successfully',
  roomsLoadedSuccessfully: 'Rooms Loaded Successfully',
  roomUpdatedSuccessfully: 'Room Updated Successfully',
  save: 'Save',
  searchplaceholder:'Search Room name or Tanent name',
  selectRoom: 'Select Room',
  selectTenant: 'Select Tenant',
  sendOtp: 'Send OTP code',
  signUp: 'Sign Up',
  startDate: 'Start Date',
  status: 'Status',
  tapAgainToExit: 'Tap again to exit',
  tenant: 'Tenant',
  toDate: 'To',
  totalAdults: 'Total Adults',
  totalChildren: 'Total Children',
  totalRent: 'Total Rent',
  tenantAddedSuccessfully: 'Tenant Added Successfully',
  tenantHome: 'Tenant Home',
  tenantName: 'Tenant Name',
  tenantDetails: 'Tenant Details',
  tenantRoomDetails: 'Tenant Room Details',
  tenantUpdatedSuccessfully: 'Tenant Updated Successfully',
  termsAndConditions: 'Terms & Conditions',
  type: 'Type',
  unpaid: 'Unpaid',
  update: 'Update',
  updateExisting: 'Update Existing',
  updateRent: 'Update Rent',
  updateRoom: 'Update Room',
  updateTenantDetails: 'Update Tenant Details',
  userDetailIncorrect: 'User Detail Incorrect. Please reopen app',
  userType: 'User Type',
  vacant: 'Vacant',
  view: 'View',
  viewPaidRents: 'View Paid Rents',
  viewAllRents: 'View All Rents',
  waterCharge: 'Water Charge',
  yes: 'Yes',
  resetPassword: 'Reset Password',
  opt: 'OTP',
  otpValidation: 'Please enter a valid 6-digit OTP.',
  mobileValidation: 'Please enter a valid 10-digit mobile number.',
  eightCharacterPasswordValidation: 'Password must be at least 8 characters long.',
  strengthPasswordValidation: 'Password must include uppercase, lowercase, and a number.',
  passwordDoesnotMatchValidation: 'Passwords do not match.',
  otpSentToMobile: 'OTP sent successfully to your mobile',
  failedToSendOTP: 'Failed to send OTP code.',
  errorOccured: 'An error occurred. Please try again later.',
  passwordResetSuccessfull: 'Password reset successful. Please log in with your new password.',
  failedToResetPassword: 'Failed to reset password. Please try again.',
  resendOtp:'Resend OTP',
  otpBlocked:'Otp send blocked. Please contact Administrator. Contact No. 9849133981',
  errorOtpInvalid: 'OTP Invalid',
  errorUserNotFound:'User not found',
  optSentEnterbelow:'OTP has been sent to you on your mobile phone. Please enter it below',
  optReSentEnterbelow:'OTP has been resent to you on your mobile phone. Please enter it below',
  profilename:'Name',
  profileuser:'User',
  profilephone:'phone'
};
