export default {
  about: 'बारे',
  aboutInfo: 'कोठाभाडा भाडामा लिने र घरबेतिको लागि भाडा व्यवस्थापन एप हो',
  all: 'सबै',
  add: 'नयाँ',
  addNew: 'नयाँ थप्नुहोस्',
  addPhoto: 'फोटो थप्नुहोस्',
  address: 'ठेगाना',
  addRent: 'भाडा थप्नुहोस्',
  addRoom: 'कोठा थप्नुहोस्',
  addUpdate: 'नयाँ/परिवर्तन',
  addUpdateTenant: 'भाडावाला नयाँ/परिवर्तन',
  alreadySignedIn: 'पहिले नै साइन इन',
  applyFilter: 'फिल्टर गर्नुहोस्',
  areYouSure: 'के तपाइँ निश्चित हुनुहुन्छ कि तपाइँ फिर्ता जान चाहनुहुन्छ?',
  areYouSureToChange: 'के तपाई परिवर्तन गर्न निश्चित हुनुहुन्छ?',
  areYouSureAboutPayment: 'तपाईं भुक्तानी बारे निश्चित हुनुहुन्छ?',
  areYouSureToDelete: 'के तपाइँ मेटाउन निश्चित हुनुहुन्छ?',
  areYouSureToLogout: 'के तपाई साँच्चै लगआउट गर्न चाहनुहुन्छ?',
  cancel: 'रद्द गर्नुहोस्',
  changePassword: 'पासवर्ड परिवर्तन',
  changeLanguage: 'भाषा परिवर्तन गर्नुहोस्',
  confirm: 'पुष्टि गर्नुहोस्',
  customerFeedback: 'ग्राहक प्रतिक्रिया',
  date: 'मिति',
  delete: 'मेटाउन',
  deletedSuccessfully: 'सफलतापूर्वक मेटियो',
  editProfile: 'प्रोफाइल सम्पादन गर',
  electricityCharge: 'बिजुली शुल्क',
  electricityPerUnit: 'प्रति युनिट बिजुली',
  electricityUnit: 'बिजुली एकाइ',
  endDate: 'अन्त्य मिति',
  english: 'English',
  enterDetails: 'विवरण प्रविष्ट गर्नुहोस्',
  enterMobile: 'कृपया मोबाइल प्रविष्ट गर्नुहोस्',
  enterName: 'कृपया नाम प्रविष्ट गर्नुहोस्',
  enterPassword: 'कृपया पासवर्ड प्रविष्ट गर्नुहोस्',
  enterPrice: 'कृपया मूल्य प्रविष्ट गर्नुहोस्',
  enterRePassword: 'कृपया पासवर्ड पुन: टाइप गर्नुहोस्',
  enterRoomName: 'कृपया कोठाको नाम प्रविष्ट गर्नुहोस्',
  enterFloor: 'कृपया फ्लोर टाइप गर्नुहोस्',
  enterUserType: 'कृपया प्रयोगकर्ता प्रकार टाइप गर्नुहोस्',
  feedback: 'प्रतिक्रिया',
  feedbackemail: 'तपाईंको इमेल लेख्नुहोस्',
  feedbackcontactnumber: 'फोन नम्बर',
  feedbackdescription: 'तपाईंको सन्देश लेख्नुहोस्....',
  forgotPassword:'पासवर्ड बिर्सनुभयो',
  feedbacksubmit: 'प्रेषण गर्नुहोस्',
  f_email: 'इमेल',
  f_contactnumber: 'सम्पर्क नम्बर',
  f_description: 'विवरण',
  flat: 'फ्लैट',
  floor: 'तल्ला',
  fromDate: 'मिति देखि',
  full: 'खाली छैन',
  fullName: 'पुरा नाम',
  garbageCharge: 'फोहोर शुल्क',
  haveAnAccount: 'खाता छ?',
  internetCharge: 'इन्टरनेट शुल्क',
  kothaVada: 'कोठाभाडा',
  landlord: 'घरधनी',
  loading: 'लोड हुँदै...कृपया पर्खनुहोस्',
  login: 'लग - इन',
  logout: 'बाहिर निस्कनु',
  matchPassword: 'पासवर्ड मिलेन',
  mobile: 'मोबाइल',
  name: 'नाम',
  nepali: 'नेपाली',
  newUser: 'नयाँ प्रयोगकर्ता',
  no: 'होइन',
  noNotifications: 'कुनै सूचना छैन',
  noPendingRents: 'कुनै बाँकी भाडा छैन',
  noRoomsAvailable: 'कुनै कोठा उपलब्ध छैन',
  notifications: 'सूचनाहरू',
  occupancy: 'भरिएको छ',
  paid: 'भुक्तान गरियो',
  paidRent: 'तिरेको भाडा',
  pay: 'तिर्नुहोस्',
  payment: 'भुक्तानी',
  password: 'पासवर्ड',
  newPassword: 'नयाँ पासवर्ड',
  confirmNewPassword: 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
  pendingRent: 'बाँकी भाडा',
  pendingRents: 'बाँकी भाडा',
  pleaseEnterRent: 'कृपया भाडा प्रविष्ट गर्नुहोस्',
  phone: 'फोन',
  previousDue: 'अघिल्लो बाँकी भाडा',
  price: 'मूल्य',
  profile: 'प्रोफाइल',
  register: 'दर्ता गर्नुहोस्',
  rent: 'भाडा',
  rentPaidSuccessfully: 'भाडा सफलतापूर्वक भुक्तान गरियो',
  rentPayment: 'भाडा भुक्तानी',
  rentDetails: 'भाडा विवरण',
  rentsLoadedSuccessfully: 'भाडा सफलतापूर्वक लोड भयो',
  rentType: 'भाडा प्रकार',
  retypePassword: 'पासवर्ड पुन: लेख्नुहोस',
  room: 'कोठा',
  roomDetails: 'कोठा विवरण',
  roomName: 'कोठाको नाम/नम्बर',
  roomRent: 'कोठा भाडा',
  roomSavedSuccessfully: 'कोठा सफलतापूर्वक सुरक्षित गरियो',
  roomsLoadedSuccessfully: 'कोठा सफलतापूर्वक लोड भयो',
  roomUpdatedSuccessfully: 'कोठा सफलतापूर्वक अपडेट गरियो',
  save: 'बचत गर्नुहोस्',
  searchplaceholder:"कोठाको नाम वा भाडामा बस्ने व्यक्तिको नाम खोज्नुहोस्",
  selectRoom: 'कोठा चयन गर्नुहोस्',
  selectTenant: 'भाडावाला चयन गर्नुहोस्',
  sendOtp: 'OTP कोड पठाउनुहोस्',
  signUp: 'साइन अप',
  startDate: 'सुरू मिति',
  status: 'स्थिति',
  tapAgainToExit: 'बाहिर निस्कन फेरि ट्याप गर्नुहोस्',
  tenant: 'भाडावाला',
  toDate: 'मिति सम्म',
  totalAdults: 'कुल वयस्कहरू',
  totalChildren: 'कुल बच्चाहरु',
  totalRent: 'कुल भाडा',
  tenantAddedSuccessfully: 'भाडावाला सफलतापूर्वक थपियो',
  tenantDetails: 'भाडावालाको विवरण',
  tenantHome: 'भाडावाला मुख्य',
  tenantName: 'भाडावालाको नाम',
  tenantRoomDetails: 'भाडावालाको कोठा विवरण',
  tenantUpdatedSuccessfully: 'भाडावाला सफलतापूर्वक अपडेट गरियो',
  termsAndConditions: 'नियम र सर्त',
  type: 'प्रकार',
  unpaid: 'भुक्तान नगरिएको',
  update: 'अपडेट',
  updateExisting: 'अवस्थित अद्यावधिक गर्नुहोस्',
  updateRent: 'भाडा अपडेट गर्नुहोस्',
  updateRoom: 'कोठा अपडेट गर्नुहोस्',
  updateTenantDetails: 'भाडावाला विवरणहरू अपडेट गर्नुहोस्',
  userDetailIncorrect: 'प्रयोगकर्ता विवरण गलत। कृपया एप पुन: खोल्नुहोस्',
  userType: 'प्रयोगकर्ता प्रकार',
  vacant: 'खाली',
  view: 'विवरण',
  viewPaidRents: 'भुक्तान गरिएको भाडा हेर्नुहोस्',
  viewAllRents: 'सबै भाडा हेर्नुहोस्',
  waterCharge: 'पानी शुल्क',
  yes: 'हो',
  resetPassword:'पासवर्ड रिसेट गर्नुहोस्',
  opt:'OTP',
  otpValidation:'कृपया एक मान्य ६-अङ्कको OTP प्रविष्ट गर्नुहोस्',
  mobileValidation:'कृपया मान्य १० अंकको मोबाइल नम्बर प्रविष्ट गर्नुहोस्',
  eightCharacterPasswordValidation:'पासवर्ड कम्तिमा 8 वर्ण लामो हुनुपर्छ',
  strengthPasswordValidation:'पासवर्डमा अपरकेस, लोअरकेस र नम्बर समावेश हुनुपर्छ',
  passwordDoesnotMatchValidation:'पासवर्डहरू मेल खाँदैनन्',
  otpSentToMobile:'तपाईंको मोबाइलमा OTP सफलतापूर्वक पठाइयो',
  failedToSendOTP:'OTP कोड पठाउन सकिएन',
  errorOccured:'एउटा त्रुटि भयो। कृपया पछि पुन: प्रयास गर्नुहोस्',
  passwordResetSuccessfull: 'पासवर्ड रिसेट सफल भयो। कृपया आफ्नो नयाँ पासवर्डको साथ लग इन गर्नुहोस्',
  failedToResetPassword: 'पासवर्ड रिसेट गर्न असफल भयो। कृपया पुन: प्रयास गर्नुहोस्',
  resendOtp:'OTP पुन: पठाउनुहोस्',
  otpBlocked:'Otp पठाउन रोक लगाइयो। कृपया प्रशासकलाई सम्पर्क गर्नुहोस्। सम्पर्क नम्बर ९८४९१३३९८१',
  errorOtpInvalid: 'अमान्य ओटीपी',
  errorUserNotFound:'प्रयोगकर्ता फेला परेन',
  optSentEnterbelow:'OTP तपाईँको मोबाइल फोनमा पठाइएको छ। कृपया तल प्रविष्ट गर्नुहोस्',
  optReSentEnterbelow:'OTP तपाईँको मोबाइल फोनमा पुनः पठाइएको छ। कृपया तल प्रविष्ट गर्नुहोस्',
  profilename: 'प्रयोगकर्ता',  
  profileuser: 'नाम',  
  profilephone: 'फोन'  

};
