import React, {useEffect, useContext, useState} from 'react';
import {
  View,
  Text,
  BackHandler,
  StyleSheet,
  Modal,
  Image,
  Pressable,
  TouchableOpacity,
  Alert,
  ToastAndroid
} from 'react-native';
import {CommonActions} from '@react-navigation/native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import {
  LANGUAGE_CODE,
  LANGUAGE_MAP,
  SCREEN_NAME,
  RESPONSE_STATUS
} from '../constants/app-constants';
import {BUTTON_COLOR, ICON_CONSTANTS} from '../constants/theme-constants';
import strings, {changeLanguage} from '../localizations/screen';
import KVAsyncStorage from '../services/KVAsyncStorage';
import KVRoomContext from '../contexts/KVRoomContext';
import KVTenantContext from '../contexts/KVTenantContext';
import KVRentContext from '../contexts/KVRentContext';
import KVUserContext from '../contexts/KVUserContext';
import KVRadioPopup from '../components/KVRadioPopup';
import {CONTAINER_COLOR, FONT_CONSTANTS} from '../constants/theme-constants';
import User from '../models/User';
import { KVUserManager } from '../contexts/KVUserManager';

export default function ProfileScreen({navigation}) {
  const [isModalVisible, setModalVisible] = useState(false);
  const [user, setUser] = useState(new User());
  const [language, setLanguage] = useState(LANGUAGE_CODE.ENGLISH);

  const userContext = useContext(KVUserContext);
  const roomContext = useContext(KVRoomContext);
  const tenantContext = useContext(KVTenantContext);
  const rentContext = useContext(KVRentContext);
  useEffect(() => {
    const backHandler = BackHandler.addEventListener(
      'hardwareBackPress',
      () => {
        navigation.pop();
        return true;
      },
    );

    return () => backHandler.remove();
  }, []);

  useEffect(() => {
    // Update the header title with the localized string
    navigation.setOptions({title: strings.profile});

    let response = userContext.getUserAndToken();
    if (response && response.userDetail) {
      setUser(response.userDetail);
      response.language
        ? setLanguage(response.language)
        : setLanguage(LANGUAGE_CODE.ENGLISH);
    }
    console.log(response);
  }, [strings.profile]);

  const logoutClicked = () => {
    Alert.alert(strings.logout + '!', strings.areYouSureToLogout, [
      {
        text: strings.no,
        onPress: () => null,
      },
      {
        text: strings.yes,
        onPress: async () => {
          await userContext.clearAllData();
          await tenantContext.clearAllData();
          await roomContext.clearAllData();
          await rentContext.clearAllData();
          await new KVAsyncStorage().clearAll();
          navigation.reset({
            index: 0,
            routes: [{name: SCREEN_NAME.LOGIN}],
          });
        },
      },
    ]);
  };

  /*
   *  method to handle language changed
   */
  const languageChanged = value => {
    Alert.alert(strings.confirm + '!', strings.areYouSureToChange, [
      {
        text: strings.no,
        onPress: () => null,
      },
      {
        text: strings.yes,
        onPress: async () => {
          await userContext.setLanguage(value);
          changeLanguage(value);
          // clears the existing navigation stack and sets a new stack
          navigation.reset({
            index: 1, // 'PROFILE' will be at index 1
            routes: [
              {name: SCREEN_NAME.TABNAVIGATOR}, // Add the previous screen
              {name: SCREEN_NAME.PROFILE}, // Current screen
            ],
          });
          setModalVisible(!isModalVisible);
        },
      },
    ]);
  };
  /*
   * Handler method for change password button
   */
  const changePasswordHandler = async () => {
    try {
      Alert.alert(strings.changePassword + '!', strings.areYouSureToChange, [
        {
          text: strings.no,
          onPress: () => null,
        },
        {
          text: strings.yes,
          onPress: async () => {
            let response = await new KVUserManager().sendAutoGeneratedOtp({
              contacts: user.mobile.toString(),
            });
            if (response.status === RESPONSE_STATUS.SUCCESS) {
              ToastAndroid.showWithGravity(
                strings.otpSentToMobile,
                ToastAndroid.SHORT,
                ToastAndroid.TOP,
              );
              navigation.navigate(SCREEN_NAME.RESETPASSWORDCONFIRMATION, {
                mobile: user.mobile,
              });
            } else {
              ToastAndroid.showWithGravity(
                strings.failedToSendOTP,
                ToastAndroid.SHORT,
                ToastAndroid.TOP,
              );
            }
          },
        },
      ]);
    } catch (error) {
      ToastAndroid.showWithGravity(
        strings.errorOccured,
        ToastAndroid.SHORT,
        ToastAndroid.TOP,
      );
      console.error('Error:', error);
    }
  };

  return (
    <View style={{flex: 1}}>
      <View style={{flex: 1, alignItems:'center'}}>
        <View style={styles.profileImageContainer}>
        <Image
          style={styles.imageStyle}
          source={require('../assets/img/profile.png')}/>
          <Ionicons
            name='camera'
            color={ICON_CONSTANTS.ICON_BUTTON_COLOR}
            size={ICON_CONSTANTS.ICON_SIZE_MEDIUM / 1.2}
            style={styles.cameraIcon}/>
        </View>
        <Text style={styles.profileName}>{user.name}</Text>
        <Text style={styles.mobile}>{user.mobile}</Text>
      </View>
      <View style={styles.contactDetail}>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={() => {
            navigation.navigate(SCREEN_NAME.EDITPROFILE);
          }}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="create-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.editProfile}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={changePasswordHandler}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="key-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.changePassword}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={() => setModalVisible(true)}>
          <Modal
            animationType="slide"
            transparent={true}
            visible={isModalVisible}
            onRequestClose={() => {
              setModalVisible(!isModalVisible);
            }}>
            <KVRadioPopup
              onCheckedChanged={value => languageChanged(value)}
              values={LANGUAGE_MAP}
              checked={language}
              onCancelClicked={() => {
                setModalVisible(!isModalVisible);
              }}
            />
          </Modal>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="globe-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.changeLanguage}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={() => {
            navigation.navigate(SCREEN_NAME.UPLOADDOCUMENTS);
          }}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="cloud-upload-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.uploadDocuments}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={() => {
            navigation.navigate(SCREEN_NAME.CUSTOMERFEEDBACK);
          }}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="chatbox-ellipses-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.customerFeedback}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={() => {
            navigation.navigate(SCREEN_NAME.ABOUT);
          }}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="help-circle-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.about}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity style={styles.contactDetailButton}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="information-circle-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.termsAndConditions}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.contactDetailButton}
          onPress={logoutClicked}>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
            }}>
            <Ionicons
              name="log-out-outline"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
            <Text style={styles.text}>{strings.logout}</Text>
          </View>
          <View>
            <Ionicons
              name="chevron-forward-sharp"
              size={ICON_CONSTANTS.ICON_SIZE_MEDIUM}
            />
          </View>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  profileImageContainer: {
    position: 'relative',
    width: '35%',
    height: '50%',
    marginTop: '2%',
    marginBottom:'4%'
  },
  imageStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 100,
  },
  profileName: {
    fontSize: FONT_CONSTANTS.FONT_SIZE_MEDIUM,
    fontWeight: 'bold',
    alignSelf: 'center',
    margin: '2%',
    marginBottom: '2%',
  },
  mobile: {
    fontSize: FONT_CONSTANTS.FONT_SIZE_MEDIUM,
    alignSelf: 'center',
  },
  contactDetail: {
    flex: 1,
    marginBottom: '50%'
  },
  text: {
    fontSize: FONT_CONSTANTS.FONT_SIZE_MEDIUM,
    marginLeft: '5%',
    padding: '1%',
    flexDirection:"row",
  },
  contactDetailButton: {
    marginHorizontal: '3%',
    marginVertical: '1%',
    paddingHorizontal: '2%',
    paddingVertical: '3%',
    flexDirection: 'row',
    backgroundColor: BUTTON_COLOR.ACTIVE,
    borderRadius: 10,
  },
  modalView: {
    marginTop: '75%',
    margin: '25%',
    backgroundColor: CONTAINER_COLOR.LIGHTGREY,
    borderRadius: 10,
    padding: '5%',
    alignItems: 'center',
  },
  cancelButton: {
    fontSize: FONT_CONSTANTS.FONT_SIZE_MEDIUM,
    backgroundColor: BUTTON_COLOR.CANCEL,
    marginTop: '5%',
    padding: '5%',
    paddingHorizontal: '20%',
    borderRadius: 10,
  },
  cameraIcon:{
    position: 'absolute',
    bottom: '2%',
    right: '0.45%',
    backgroundColor: ICON_CONSTANTS.ICON_BORDER_COLOR,
    padding: '5%',
    width: '24%',
    height: '24%',
    borderRadius: 100,
  }
});
